---
language: python
python: "2.7"

# Use the new container infrastructure
dist: trusty
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version
script:
  # Basic role syntax check
  - ansible-galaxy install -r requirements.http.yml
  - ansible-playbook task.yml -i test/hostfile --syntax-check

cache: 
  pip: true
